Fix missing import (#189)
Addresses the following error when running ollama:
```
Traceback (most recent call last):
  File "C:\Users\kalin\Work\gaia/src/gaia/interface/widget.py", line 111, in do_work
    self.initialize_servers()
  File "C:\Users\kalin\Work\gaia/src/gaia/interface/widget.py", line 155, in initialize_servers
    self.initialize_agent_server()
  File "C:\Users\kalin\Work\gaia/src/gaia/interface/widget.py", line 202, in initialize_agent_server
    target=getattr(agents, selected_agent.lower()),
AttributeError: module 'gaia.agents' has no attribute 'llm'
```