Gaia Installer Improvements (#458)
- [x] Fix logging during pip install inside the gaia installer which was
being truncated and difficult to troubleshoot (used `DetailPrint` and
`ExecToLog`)
- [x] Fix installer error on specific platforms due to `docopt` and
setup tools circular dependency when running `pip install` inside NSIS
- [x] Created batch file for running all pip install commands to fix log
buffer overflow and docopt dependency error
- [x] Move logs from terminal into window output, also allows easy
copy-paste
- [x] Add more informative messages when build fails, allow users to
copy-paste log on failure
- [x] Include contact info (gaia@amd.com) when installation fails
- [x] Improve `BuildInstaller.ps1` script, used extensively in testing
the installer
- [x] Install ollama if not found
- [x] Make driver check more strict due to incompatible driver ver
`.240`
- [x] Fix header from being clipped due to long string
- [x]  Fixes the following error observed by 3 users:
```
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\kovtchar\AppData\Local\Temp\pip-req-build-lszzn557\setup.py", line 3, in <module>
      from docopt import __version__
  ModuleNotFoundError: No module named 'docopt'
```

cc: @itomek, @jeremyfowers 

closes #457, #459, #450